In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\HP\Downloads\\archive (1)\\Ecommerce Purchases")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\HP\AppData\Local\Temp\ipykernel_16872\2114349057.py:1: SyntaxWarning: invalid escape sequence '\D'
  df=pd.read_csv("C:\\Users\\HP\Downloads\\archive (1)\\Ecommerce Purchases")

In [3]:
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [4]:
df.tail()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [5]:
df["AM or PM"]=df["AM or PM"].astype('category')
df["CC Provider"]=df["CC Provider"].astype("category")
df["Job"]=df["Job"].astype("category")
df["Language"]=df["Language"].astype("category")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  category
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  category
 9   Email             10000 non-null  object
 10  Job               10000 non-null  category
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  category
 13  Purchase Price    10000 non-null  float64
dtypes: category(4), float64(1), int64(2), object(7)
memory usage: 852.1+ KB

In [7]:
df.size

140000

In [8]:
df.shape

(10000, 14)

In [9]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [10]:
df.dtypes

Address               object
Lot                   object
AM or PM            category
Browser Info          object
Company               object
Credit Card            int64
CC Exp Date           object
CC Security Code       int64
CC Provider         category
Email                 object
Job                 category
IP Address            object
Language            category
Purchase Price       float64
dtype: object

## Questions

In [11]:
# 1. Display Top 10 Rows of The Dataset
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

In [12]:
# 2. Display last 10 Rows of The Dataset
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [13]:
# 3.Check data type of each column
# df.info()
df.dtypes

Address               object
Lot                   object
AM or PM            category
Browser Info          object
Company               object
Credit Card            int64
CC Exp Date           object
CC Security Code       int64
CC Provider         category
Email                 object
Job                 category
IP Address            object
Language            category
Purchase Price       float64
dtype: object

In [14]:
# 4.How many rows and columns are in our dataset 
df.shape

(10000, 14)

In [15]:
# 5.Check null values in the dataset
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [16]:
for i in df.columns:
    print(f"The null values in {i} column is {df[i].isnull().sum()}")

The null values in Address column is 0
The null values in Lot column is 0
The null values in AM or PM column is 0
The null values in Browser Info column is 0
The null values in Company column is 0
The null values in Credit Card column is 0
The null values in CC Exp Date column is 0
The null values in CC Security Code column is 0
The null values in CC Provider column is 0
The null values in Email column is 0
The null values in Job column is 0
The null values in IP Address column is 0
The null values in Language column is 0
The null values in Purchase Price column is 0

In [17]:
# 6.Highest and lowest purchase price 
df.head(3)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95

In [18]:
max_purchase=df['Purchase Price'].max()
print(f"The highest purchase price is {max_purchase}")

The highest purchase price is 99.99

In [19]:
min_purchase=df['Purchase Price'].min()
print(f"The lowest purchase price is {min_purchase}")

The lowest purchase price is 0.0

In [20]:
# 7.Average purchase Price
avg_purchase=df['Purchase Price'].mean()
print(f"The average Purchase Price is {avg_purchase}")

The average Purchase Price is 50.347302

In [21]:
df.sample(6)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
5368,"096 Anderson Club Apt. 728\nLisahaven, GU 69703",77 WB,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_8...,"Olson, Rowland and Allen",210048342104861,05/26,914,Discover,odonnellerin@hotmail.com,Scientific laboratory technician,113.219.37.198,de,5.95
3578,"708 Thomas Bypass Apt. 632\nMyersland, VT 19437",20 KY,AM,Opera/9.62.(Windows CE; sl-SI) Presto/2.9.162 ...,Donovan LLC,3112320869763202,09/24,46,Voyager,davidrodriguez@friedman.biz,Careers adviser,95.241.94.180,ru,77.96
8989,"285 Flynn Court\nMichellehaven, NV 76448",55 mF,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5360...,Fernandez and Sons,869906643681727,07/22,4520,Voyager,skinnermichelle@yahoo.com,Cartographer,174.244.254.106,zh,12.23
8086,"308 Kim Common Apt. 774\nEast Luis, UT 95485",64 KF,PM,Opera/8.85.(Windows NT 5.01; it-IT) Presto/2.9...,Costa-Hill,676297119528,09/25,101,Mastercard,usmith@smith.org,Land/geomatics surveyor,104.241.171.48,ru,49.62
1536,"455 Chelsea Pass\nBirdborough, UT 92451-6248",90 td,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Monroe-Nelson,561281931452,09/16,413,VISA 16 digit,nathanclark@brown.info,Forest/woodland manager,107.166.159.236,ru,76.54
6630,"905 Michael Vista Apt. 970\nRussellbury, IN 35...",37 No,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_5...,Wilson-Vasquez,375628804541642,04/19,565,Diners Club / Carte Blanche,michellefoster@hotmail.com,"Research officer, political party",124.119.71.66,pt,95.13

In [22]:
# 8.how many people have french 'fr' as their language
df[df['Language']=='fr'].shape[0]

1097

In [23]:
# 9.Job title contains Enginner
df[df['Job'].str.contains('engineer',case=False)].shape[0]

984

In [24]:
# 10.Find The Email of the person with the following IP Address: 132.207.160.22
mask1=df[df['IP Address']=='132.207.160.22']
print(f"The Email of following IP Address 132.207.160.22 is:{mask1['Email']}")

The Email of following IP Address 132.207.160.22 is:2    amymiller@morales-harrison.com
Name: Email, dtype: object

In [25]:
# 11.How many People have Mastercard as their Credit Card Provider and made a purchase above 50?
df.loc[(df['CC Provider']=='Mastercard') & (df["Purchase Price"]>50)].shape[0]

405

In [26]:
# 12.Find the email of the person with the following Credit Card Number: 4664825258997302
df[df['Credit Card']==4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: object

In [27]:
# 13.How many people purchase during the AM and how many people purchase during PM?
# Method 1
mask2=df[df['AM or PM']=='AM'].shape[0]
print(f"The people how purchase during the AM is {mask2}")

mask3=df[df["AM or PM"]=='PM'].shape[0]
print(f"The people how purchase during the PM is {mask3}")

print(mask2+mask3)

The people how purchase during the AM is 4932
The people how purchase during the PM is 5068
10000

In [28]:
# Method 2
df["AM or PM"].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

In [29]:
# 14.How many people have a credit card that expires in 2020?
# method 1
def func():
    count=0
    for date in df["CC Exp Date"]:
        if date.split('/')[1]=='20':
            count=count+1
    print(count)

func()

988

In [30]:
# method 2
df[df['CC Exp Date'].apply(lambda x:x[3:]=='20')].shape[0]

988

In [31]:
# 15.What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...)
list=[]
for email in df['Email']:
    emails=email.split('@')[1]
    list.append(emails)

df['temp']=list

In [32]:
df['temp'].value_counts(ascending=False).head(5)

temp
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

In [33]:
# method 2
df['Email'].apply(lambda X:X.split('@')[1]).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

In [34]:
split=lambda x:x.split('@')[1]
df['Email'].apply(split).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

In [35]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,temp
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com